# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190622_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
